const colleges = [
  'Harvard University',
  'Stanford University',
  'Massachusetts Institute of Technology',
  'University of California, Berkeley',
  'California Institute of Technology',
  'University of Oxford',
  'University of Cambridge',
  'Princeton University',
  'Columbia University',
  'University of Chicago',
  'Yale University',
  'University of Pennsylvania',
  'Cornell University',
  'University of Michigan',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of California, Santa Barbara',
  'University of California, Davis',
  'University of California, Irvine',
  'University of Southern California',
  'New York University',
  'Duke University',
  'Northwestern University',
  'Johns Hopkins University',
  'University of Washington',
  'University of Texas at Austin',
  'University of Illinois at Urbana-Champaign',
  'University of Wisconsin-Madison',
  'University of North Carolina at Chapel Hill',
  'University of Florida',
  'Pennsylvania State University',
  'Ohio State University',
  'University of Minnesota',
  'Purdue University',
  'Georgia Institute of Technology',
  'University of Maryland',
  'University of Pittsburgh',
  'University of Virginia',
  'University of Arizona',
  'Indiana University',
  'Michigan State University',
  'University of Colorado Boulder',
  'University of Georgia',
  'University of Iowa',
  'University of Miami',
  'University of Missouri',
  'University of Nebraska-Lincoln',
  'University of Oklahoma',
  'University of Oregon',
  'University of South Carolina',
  'University of Tennessee',
  'University of Utah',
  'University of Kansas',
  'University of Kentucky',
  'University of Alabama',
  'University of Arkansas',
  'University of Mississippi',
  'University of Nevada, Las Vegas',
  'University of New Mexico',
  'University of Wyoming',
  'Auburn University',
  'Clemson University',
  'Florida State University',
  'Louisiana State University',
  'Mississippi State University',
  'North Carolina State University',
  'Oklahoma State University',
  'Texas A&M University',
  'University of Connecticut',
  'University of Delaware',
  'University of Hawaii',
  'University of Idaho',
  'University of Illinois Chicago',
  'University of Louisville',
  'University of Massachusetts Amherst',
  'University of Montana',
  'University of New Hampshire',
  'University of North Dakota',
  'University of Rhode Island',
  'University of Vermont',
  'University of Wisconsin Milwaukee',
  'Baylor University',
  'Brigham Young University',
  'Dartmouth College',
  'Emory University',
  'Georgetown University',
  'Rice University',
  'Vanderbilt University',
  'Wake Forest University',
  'Washington University in St. Louis',
  'Williams College',
  'Amherst College',
  'Swarthmore College',
  'Pomona College',
  'Wellesley College',
  'Middlebury College',
  'Carleton College',
  'Bowdoin College',
  'Claremont McKenna College',
  'Haverford College',
  'Vassar College',
  'Davidson College',
  'Wesleyan University',
  'Grinnell College',
  'Hamilton College',
  'Colgate University',
  'Colby College',
  'Bates College',
  'University of Richmond',
  'Bucknell University',
  'Lafayette College',
  'Oberlin College',
  'Smith College',
  'Bryn Mawr College',
  'Colorado College',
  'Mount Holyoke College',
  'Macalester College',
  'Kenyon College',
  'Scripps College',
  'Trinity College',
  'Skidmore College',
  'Union College',
  'Gettysburg College',
  'Franklin and Marshall College',
  'Occidental College',
  'Rhodes College',
  'Sarah Lawrence College',
  'Whitman College',
  'Denison University',
  'Connecticut College',
  'Dickinson College',
  'Furman University',
  'College of the Holy Cross',
  'Sewanee: The University of the South',
  'St. Lawrence University',
  'St. Olaf College',
  'Wheaton College',
  'College of Wooster',
  'DePauw University',
  'Knox College',
  'Lawrence University',
  'Hobart and William Smith Colleges',
  'Gustavus Adolphus College',
  'Centre College',
  'Hendrix College',
  'Lake Forest College',
  'Transylvania University',
  'Willamette University',
  'University of Puget Sound',
  'Augustana College',
  'Kalamazoo College',
  'Allegheny College',
  'Ripon College',
  'Beloit College',
  'Illinois Wesleyan University',
  'Monmouth College',
  'Northland College',
  'Cornell College',
  'Earlham College',
  'Albion College',
  'Coe College',
  'Hanover College',
  'Hope College',
  'Westminster College',
  'Wittenberg University',
  'Randolph-Macon College',
  'Ohio Wesleyan University',
  'Wabash College',
  'Wartburg College',
  'Concordia College',
  'Grove City College',
  'Goucher College',
  'Hartwick College',
  'Washington & Jefferson College',
  'Virginia Wesleyan University',
  'Westminster College',
  'Goshen College',
  'Pacific Lutheran University',
  'St. Norbert College',
  'Southwestern University',
  'University of Dallas',
  'Ursinus College',
  'Wheaton College Massachusetts',
  'Whittier College',
];

export default colleges;
